### ISSUE TITLE
Can delete this code "preds = preds.squeeze(2)"?

### ISSUE THREAD

**Issue by zoe218** [meijieru/crnn.pytorch#102]
Traceback (most recent call last):
  File "./crnn_main.py", line 228, in <module>
    val(crnn, test_dataset, criterion)
  File "./crnn_main.py", line 176, in val
    preds = preds.squeeze(2)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 750, in squeeze
    return Squeeze.apply(self, dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/tensor.py", line 378, in forward
    result = input.squeeze(dim)
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

**Comment by meijieru** [comment]
Sorry, but I could not reproduce your error.

**Comment by rabbithui** [comment]
@zoe218 Did you solve the problem? I get the same issue

**Comment by 1711120070** [comment]
same problem

**Comment by zoe218** [comment]
I deleted the code “preds = preds.squeeze(2)” @ rabbithui

**Comment by Tangent-Wei** [comment]
@zoe218 After deleted the code "preds = preds.squeeze(2) ", my val-loss can't  be decreased, even increased,  though train-loss is decreased.val and train data are come from the same distribution.

**Comment by Aurora11111** [comment]
I delete it,and work well!

**Comment by MarStarck** [comment]
using python 3.6, pytorch 0.4 will meet the problem, preds is 26*64 and cannot be squeezed.

**Comment by ZimingLu** [comment]
> using python 3.6, pytorch 0.4 will meet the problem, preds is 26*64 and cannot be squeezed.
> 
> I delete it but the loss is always 0. @Aurora11111 did you meet the problem?

hello, I delete this line and it works fine for me. Have generated dataset correctly? I use the dataset here and I hope this can help u :).  https://github.com/marvis/ocr_attention
