### ISSUE TITLE
KeyError: '\xe5'

### ISSUE THREAD

**Issue by DLUTfangping** [meijieru/crnn.pytorch#121]
Traceback (most recent call last):
  File "crnn_main.py", line 204, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "crnn_main.py", line 183, in trainBatch
    t, l = converter.encode(cpu_texts)
  File "/data8T/fangping/crnn.pytorch/utils.py", line 51, in encode
    text, _ = self.encode(text)
  File "/data8T/fangping/crnn.pytorch/utils.py", line 45, in encode
    for char in text
KeyError: '\xe5'
@meijieru @ZhangXinNan @Weihnachtswurst 
when I training it happens and the training data contains chinese

**Comment by meijieru** [comment]
It looks like python2's coding problem. Use python3 instead.

**Comment by ZhuLingfeng1993** [comment]
Do you solve the problem?What's the solution?
