### ISSUE TITLE
在pytorch 0.4分支中，训练时出现了问题，NameError: name 'image' is not defined

### ISSUE THREAD

**Issue by WenmuZhou** [meijieru/crnn.pytorch#126]
```sh
Traceback (most recent call last):
  File "/data/zj/crnn.pytorch-pytorch-0.4/train.py", line 175, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "/data/zj/crnn.pytorch-pytorch-0.4/train.py", line 153, in trainBatch
    utils.loadData(image, cpu_images)
NameError: name 'image' is not defined

```

**Comment by meijieru** [comment]
这部分还没完成。。

**Comment by WenmuZhou** [comment]
那我先fork一个改改试试，我有个问题想请教一下，CTCLoss传进去打值需要时cpu上的还是gpu上的

**Comment by meijieru** [comment]
CTCLoss cpu/gpu 都有，但不知道现在有没有 pytorch 0.4 的binding。

**Comment by WenmuZhou** [comment]
我在0.4上，传gpu的数据过去，程序会卡死，cpu就是正常的

**Comment by meijieru** [comment]
先用master分支吧，0.4也只是可以简化一部分代码

**Comment by WenmuZhou** [comment]
ok

**Comment by meijieru** [comment]
能否传我一份简单的训练测试集，改一下训练代码，谢谢

**Comment by WenmuZhou** [comment]
我有个fork是改好的，但是不能提交pr，网页提示有错误
>There isn’t anything to compare.
>meijieru:master and WenmuZhou:master are entirely different commit histories.

**Comment by meijieru** [comment]
你需要先rebase到我的master分支

**Comment by WenmuZhou** [comment]
我提交了pr，你看看
