### ISSUE TITLE
pytorch 训练出错，shuffle 和 sampler同时有值

### ISSUE THREAD

**Issue by xikunlun001** [meijieru/crnn.pytorch#128]
试了pytorch 0.2, 0.4版本  都是同样错误。看了下貌似是不能同时shuffle和sampler，请问这个情况如何解决呢
@meijieru @ZhangXinNan @Weihnachtswurst 

Traceback (most recent call last):
  File "crnn_main.py", line 69, in <module>
    collate_fn=dataset.alignCollate(imgH=opt.imgH, imgW=opt.imgW, keep_ratio=opt.keep_ratio))
  File "/home/chenxi/.conda/envs/chinese-ocr/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 287, in __init__
    raise ValueError('sampler is mutually exclusive with shuffle')
ValueError: sampler is mutually exclusive with shuffle

**Comment by dalindalin** [comment]
之前有人问，详见 https://github.com/meijieru/crnn.pytorch/issues/55
