### ISSUE TITLE
我试图将网络写入tensorboard时，出现了下面的错误

### ISSUE THREAD

**Issue by WenmuZhou** [meijieru/crnn.pytorch#131]
```sh
Traceback (most recent call last):
  File "/data/zj/github/crnn.pytorch/train.py", line 193, in <module>
    train(opt)
  File "/data/zj/github/crnn.pytorch/train.py", line 106, in train
    writer.add_graph(model=net, input_to_model=dummy_input)
  File "/home/tx/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 419, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/tx/anaconda3/lib/python3.6/site-packages/tensorboardX/graph.py", line 85, in graph
    list_of_nodes = parse(graph)
  File "/home/tx/anaconda3/lib/python3.6/site-packages/tensorboardX/graph.py", line 19, in parse
    assert n.scopeName() != '', '{} has empty scope name'.format(n)
AssertionError: %106 : Dynamic = onnx::Shape(%69)
 has empty scope name
```
出错的语句是·BidirectionalLSTM·‘中的 output = output.view(T, b, -1)’，我单步调试到这里的时候，这个操作的scope name确实是空的，请问我怎么可以给这个操作一个名字

**Comment by meijieru** [comment]
没有尝试过，用的哪一个包写到tensorboard里？

**Comment by WenmuZhou** [comment]
[tensorboardX](https://github.com/lanpa/tensorboard-pytorch)，用这个包写的

**Comment by WenmuZhou** [comment]
作者有解决思路吗
