### ISSUE TITLE
RuntimeError: expected Variable or None (got torch.cuda.FloatTensor)

### ISSUE THREAD

**Issue by Aurora11111** [meijieru/crnn.pytorch#152]
Now I have read in my lmdb datesets ,but occurs errors at here:
Traceback (most recent call last):
  File "/home/rice/PycharmProjects/crnn.pytorch-master/crnn_main.py", line 203, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "/home/rice/PycharmProjects/crnn.pytorch-master/crnn_main.py", line 189, in trainBatch
    cost.backward()
  File "/home/rice/.local/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/rice/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: expected Variable or None (got torch.cuda.FloatTensor)

Process finished with exit code 1
anyone who know this issue?

**Comment by Aurora11111** [comment]
I have checked that my pytorch veriosn is 0.4.0,and modified the init.py in warp_ctc,still the same issue occurs.

**Comment by Aurora11111** [comment]
It is the same problem as #133 ,but I I have checked that my pytorch veriosn is 0.4.0,and modified the init.py in warp_ctc,still the same issue occurs.

**Comment by meijieru** [comment]
See #133
