### ISSUE TITLE
TypeError: 'required' is an invalid argument for positionals with crnn_main.py 

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [meijieru/crnn.pytorch#17]
Hello,
After creating my own dataset with create_dataset.py l got the following : 
**/train_directory**  which contains  data-train.mdb & lock-train.mdb
**/test_directory**  which contains data-test.mdb & lock-train.mdb

then while  l run  `crnn_main.py ` l get the following error :  

```
python2 crnn_main.py [--param val]
Traceback (most recent call last):
  File "crnn_main.py", line 18, in <module>
    parser.add_argument('/home/ahmed/Downloads/sample/output/train', required=True, help='path to dataset')
  File "/home/ahmed/anaconda3/envs/cv/lib/python2.7/argparse.py", line 1276, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
  File "/home/ahmed/anaconda3/envs/cv/lib/python2.7/argparse.py", line 1388, in _get_positional_kwargs
    raise TypeError(msg)
TypeError: 'required' is an invalid argument for positionals
```

Error related with : 
```
parser = argparse.ArgumentParser()
parser.add_argument('/home/ahmed/Downloads/sample/output/train', required=True, help='path to dataset')
parser.add_argument('/home/ahmed/Downloads/sample/output/test', required=True, help='path to dataset')
```

What's wrong ?

**Comment by meijieru** [comment]
You should replace val in `[]` for your purpose.

**Comment by ahmedmazari-dhatim** [comment]
@meijieru, **val in [ ]**  do you mind clarifying that ?

Thanks

**Comment by ahmedmazari-dhatim** [comment]
if you mean this : 
` python2 crnn_main.py [--param home/ahmed/Downloads/sample/output/train /home/ahmed/Downloads/sample/output/test]
`
l get the same error
