### ISSUE TITLE
A question about NoneType

### ISSUE THREAD

**Issue by softwaregitgub** [meijieru/crnn.pytorch#196]
Traceback (most recent call last):
  File "/home/stay/Desktop/CrnnPytorch/train.py", line 201, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "/home/stay/Desktop/CrnnPytorch/train.py", line 176, in trainBatch
    data = train_iter.next()
  File "/home/stay/anaconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/stay/anaconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/stay/anaconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/stay/anaconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/stay/Desktop/CrnnPytorch/dataset.py", line 51, in __getitem__
    buf.write(imgbuf)
TypeError: a bytes-like object is required, not 'NoneType'

cuda --->9.0
cudnn ---7
torch -->1.0.1

I don't know what caused it. Thank you for your answer.
 My data set is converted from Python 3 to MDB format. Is that the reason? Is it sometimes empty when buf. write () reads the binary?

**Comment by softwaregitgub** [comment]
but,when i use python2 to make mdb still have this wrong?

**Comment by softwaregitgub** [comment]
and  i use other's correct mdb still have this question,so it should not be the problem of data.

**Comment by sunsun0** [comment]
I have the same question.Have you solved it?

**Comment by softwaregitgub** [comment]
> I have the same question.Have you solved it?

No, i don't know how to solve it? Do you have any ideas?

**Comment by junkojunko** [comment]
hello have you solved it?

**Comment by sunsun0** [comment]
> > I have the same question.Have you solved it?
> 
> No, i don't know how to solve it? Do you have any ideas?

**Comment by sunsun0** [comment]
i have solved it. Use python2 to make mdb, the problem did not arise.

**Comment by softwaregitgub** [comment]
i change the dataset.py=======> return self.nSamples + 1 to  self.nSamples, and it works.

**Comment by Holmeyoung** [comment]
Try this, i rewrite it in python3 and fix bug.
https://github.com/Holmeyoung/crnn_pytorch

**Comment by LeiGan0215** [comment]
> i change the dataset.py=======> return self.nSamples + 1 to self.nSamples, and it works.

thank you,this truely soved my problem

**Comment by FortuneSeeker** [comment]
> > i change the dataset.py=======> return self.nSamples + 1 to self.nSamples, and it works.
> 
> thank you,this truely sove my problem
Hello, which interpreter do you use, python2 or python3?

**Comment by FortuneSeeker** [comment]
When training my own dataset, I got this  problem:
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    train_dataset = dataset.lmdbDataset(root=opt.trainRoot)
  File "/home/haha/Documents/Workspaces/Workspace-PyCharm/crnn-pytorch/dataset.py", line 32, in __init__
    nSamples = int(txn.get('num-samples'.encode()))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
What should I do?

**Comment by zhangfengyo** [comment]
i have also meet the same mistake, and i change the way __getitem__ do, finally it work. maybe it is why i create the dataset in a wrong way
