### ISSUE TITLE
'alphate' change to 'self.alphabet'

### ISSUE THREAD

**Issue by fsluckymao** [meijieru/crnn.pytorch#198]
Hi:@meijieru 
https://github.com/meijieru/crnn.pytorch/blob/d3a47f91691b31b8d5336e2ed5932e6cf65142f0/utils.py#L28
I deem here 'alphate' need change to 'self.alphabet'

Otherwise it may cause following problem.
Traceback (most recent call last):
  File "zhaoyuanying.py", line 84, in <module>
    t, l = converter.encode(cpu_texts)#,scanned=False)
  File "/home/mcht/tmp/crnn_pytorch/utils.py", line 84, in encode
    for char in text
  File "/home/mcht/tmp/crnn_pytorch/utils.py", line 84, in <listcomp>
    for char in text
KeyError: '-'

**Comment by meijieru** [comment]
It's intended to be that. Since your label should not contains `-` character.

**Comment by fsluckymao** [comment]
I get it
Thanks!

**Comment by leigaoxiang** [comment]
but my data need recoginise '-'?? whether should i change '-'?

**Comment by fsluckymao** [comment]
@leigaoxiang :
You can try blank to separate them
