### ISSUE TITLE
assert index <= len(self), 'index range error' AssertionError: index range error

### ISSUE THREAD

**Issue by shucunt** [meijieru/crnn.pytorch#204]
Traceback (most recent call last):
  File "train.py", line 217, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 191, in trainBatch
    data = train_iter.next()
  File "lll/venv/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "nnn/crnn.pytorch/dataset.py", line 112, in __getitem__
    return self[index + 1]
File "nnn/crnn.pytorch/dataset.py", line 75, in __getitem__
    assert index <= len(self), 'index range error'
AssertionError: index range error

**Comment by chenyanghe** [comment]
请问你这个问题解决了吗？我也遇到了这个问题

**Comment by shucunt** [comment]
> 请问你这个问题解决了吗？我也遇到了这个问题

没有解决，后来就没有再搞这个了

**Comment by blair2020** [comment]
一模一样的错误，请问楼主解决了吗，我觉得可能是lmdb，我就改了这个就报这个错误

**Comment by blair2020** [comment]
我解决了，线程数改为0
