### ISSUE TITLE
TypeError: can't pickle Environment objects?

### ISSUE THREAD

**Issue by fengheyiyi** [meijieru/crnn.pytorch#213]
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    train_iter = iter(train_loader)
  File "C:\Users\ling\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\ling\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "C:\Users\ling\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\ling\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\ling\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\ling\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\ling\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
 **TypeError: can't pickle Environment objects**

(base) C:\Users\ling\Desktop\crnn.pytorch-master\crnn.pytorch-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ling\Anaconda3\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\ling\Anaconda3\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] 拒绝访问。

**Comment by youde2000** [comment]
我也遇到同样的问题，请问解决了吗
