### ISSUE TITLE
出现报错RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by HanazawaKanana** [meijieru/crnn.pytorch#236]
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 186, in trainBatch
    cost.backward()
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 51, in backward
    _grad_output = grad_output.to(ctx.grads.device)
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by fantasyfulan** [comment]
我训练时也出现了类似的错误，请问你这个错误解决了吗。

**Comment by alnah005** [comment]
Try decreasing batch size. Sources: pytorch/pytorch#46974 and pytorch/pytorch#21819

**Comment by sssimpleboy** [comment]
> Try decreasing batch size. Sources: [pytorch/pytorch#46974](https://github.com/pytorch/pytorch/issues/46974) and [pytorch/pytorch#21819](https://github.com/pytorch/pytorch/issues/21819)

my batchsize is one,but failed
