### ISSUE TITLE
训练自己的数据时报错：an illegal memory access was encountered

### ISSUE THREAD

**Issue by fantasyfulan** [meijieru/crnn.pytorch#241]
我用create_dataset.py处理了自己的训练数据，然后放入CRNN中训练，出现以下错误：
/crnn_net/dataset.py:95: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  batch_index = random_start + torch.range(0, self.batch_size - 1)
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorMath.cu line=26 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "train.py", line 201, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "train.py", line 187, in trainBatch
    crnn.zero_grad()
  File "/crnn_net/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1114, in zero_grad
    p.grad.zero_()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generic/THCTensorMath.cu:26
我不知道什么原因导致了这个错误，也不知道怎么处理，望告知，

**Comment by alnah005** [comment]
Try decreasing batch size. Sources: https://github.com/pytorch/pytorch/issues/46974 and https://github.com/pytorch/pytorch/issues/21819
