### ISSUE TITLE
RuntimeError when launching demo.py

### ISSUE THREAD

**Issue by hellbago** [meijieru/crnn.pytorch#39]
When i try to launch demo.py i get this error:
Traceback (most recent call last):
  File "demo.py", line 30, in <module>
    preds = preds.squeeze(2)
  File "/home/ubuntu-andrea/pytorchGPU3/lib/python3.5/site-packages/torch/autograd/variable.py", line 717, in squeeze
    return Squeeze.apply(self, dim)
  File "/home/ubuntu-andrea/pytorchGPU3/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 375, in forward
    result = input.squeeze(dim)
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

What could be the problem? @meijieru

**Comment by meijieru** [comment]
Please check out previous issue first before open a new one, thanks.
