### ISSUE TITLE
Multi-gpu in training crnn model.

### ISSUE THREAD

**Issue by SnailTyan** [meijieru/crnn.pytorch#63]
When I use multi-gpu training crnn model, the accuary is incorrect. But when I use single gpu training crnn model the accuary is correct. 
Can you fix it? @meijieru

**Comment by catmonkeylee** [comment]
When I use multi-gpu ( --ngpu 4 ) to train the model, I get this error:

Traceback (most recent call last):
  File "crnn_main.py", line 197, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "crnn_main.py", line 180, in trainBatch
    preds = crnn(image)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
    return self.gather(outputs, self.output_device)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 73, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 50, in gather
    return gather_map(outputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 46, in gather_map
    return Gather(target_device, dim=dim)(*outputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 39, in forward
    return comm.gather(inputs, self.dim, self.target_device)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 188, in gather
    "but expected {}".format(got, expected))
ValueError: gather got an input of invalid size: got 26x2x37, but expected 26x4x37

But when I use single gpu to train, everything is ok.

**Comment by SDASDASA** [comment]
i also meet the same situation with @SnailTyan ,
When I use multi-gpu training crnn model, the accuary is incorrect. But when I use single gpu the result is correct.
Can you fix it? @meijieru 
thanks.

**Comment by zylxadz** [comment]
I meet the same situation,too.
The accuary is  incorrect when using multi gpu, while correct when using single gpu.
Can you fix it? @meijieru
Thanks a lot.

**Comment by rohun-tripathi** [comment]
Has this been fixed? How off is the accuracy? I haven't trained this code on multiple GPU yet, but might do that and can have a look at the issue, if the issue is not resolved

**Comment by meijieru** [comment]
[This](https://pytorch.org/docs/stable/notes/faq.html#my-recurrent-network-doesn-t-work-with-data-parallelism) May help

**Comment by zengxianyu** [comment]
I encountered the same problem

**Comment by vinayakkailas** [comment]
Any update on this issue?
