### ISSUE TITLE
KeyError: 'unexpected key "module.cnn.conv0.weight" in state_dict'

### ISSUE THREAD

**Issue by LWLucky** [meijieru/crnn.pytorch#87]
@meijieru I use my dataset to train a new model ,then run demo.py ,it occurs 
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    model.load_state_dict(torch.load(model_path))
  File "/home/hust/anaconda3/envs/lw1/lib/python2.7/site-packages/torch/nn/modules/module.py", line 331, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.cnn.conv0.weight" in state_dict'

**Comment by axzhcode** [comment]
@LWLucky you can see previews closed issues.
https://github.com/meijieru/crnn.pytorch/issues/60

**Comment by meijieru** [comment]
duplicate #60
